### ISSUE TITLE
Add a default database to connect

### ISSUE THREAD

**Issue by Linicks** [hamiltop/rethinkdb-elixir#46]
@hamiltop ,

This was mentioned in issue #31, and I thought I would add it as an issue so that it didn't slip through the cracks.  I didn't see this as part of an existing issue, but could have easily overlooked it.    

"... connect doesn't currently accept a default database..."

**Comment by hamiltop** [comment]
Thanks. We'll have to see how existing drivers do this. I think they may just call `use(database)` right away.

**Comment by hamiltop** [comment]
There's an interesting implementation issue here due to the way Connections are architected. Currently, a query is serialized before being sent to the Connection object. That means that a default db is not known at query serialization. Shifting the logic into the connection object may be our best bet.

**Comment by hamiltop** [comment]
Done.
