### ISSUE TITLE
Possibility for an Ecto Adapter?

### ISSUE THREAD

**Issue by jeregrine** [hamiltop/rethinkdb-elixir#6]
While rethinkdb isn't strictly a sql database I feel like several of the querying functions could map pretty cleanly to ecto. Most of the functions for adapters end up here https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex

Just curious what your thoughts are @hamiltop since you have intimate knowledge now of the API and its querying language.

**Comment by hamiltop** [comment]
It could definitely be done. I'm not personally heading in that direction
though. ReQL isn't really a query language like SQL or mongos query
language. It's more a defined protocol plus some guidelines for client
development.

Rather than mapping Ecto to Exrethinkdb.Query, I would just use
Exrethinkdb.Connection and build a new serialization layer going from
Ecto's api to the over the wire format. You could cherry pick bits and
pieces from Exrethinkdb.Query, but you wouldn't want to go completely from
Ecto to Exrethinkdb, as that just provides one more possible point of leaky
abstraction.

**Comment by nurugger07** [comment]
I would prefer to see this library be it's own solution and optimize for ReQL. This would give the most flexibility as changes come about in ReThink & ReQL.

**Comment by gullitmiranda** [comment]
I'm thinking of upgrading the project https://github.com/azukiapp/ecto-rethinkdb to use `exrethinkdb`. For I am with plans to use the rethinkdb in a project I'm starting.

**Comment by hamiltop** [comment]
I would love to see a "what I want from ecto-rethinkdb" list. I'm not sure I understand the use case.

**Comment by gullitmiranda** [comment]
My goal to have 'ecto-rethinkdb` is to facilitate integration with the Phoenix. I am beginning to study elixir and Phoenix, I believe it can be something useful.

It makes sense to you @hamiltop?

**Comment by hamiltop** [comment]
I think that is the wrong way to approach this.

"We need X because Phoenix works with X"

My understanding is that each piece of functionality you want is or can be
modular enough in Ecto and Phoenix to cherry pick.

So what specific functionality do you want from rethinkdb and phoenix?

**Comment by gullitmiranda** [comment]
I see your point, I am new to the world of elixir, but plan to use the rethinkdb instead of Postgres. I go to create a realtime application to management links (bookmarks).

I enjoyed the way the phoenix leaves transparent the use of Postgres, and if possible it would be interesting to rethinkdb. I believe it can facilitate much to the adoption of rethinkdb for those working with the phoenix.

**Comment by hamiltop** [comment]
But what does it add that's not already there?

You can use Ecto Validations with any model (database persistence is not required), for example. Just start using it.

You should be able to use rethinkdb without any problem with phoenix.

**Comment by gullitmiranda** [comment]
Yes, I can, but does not provide the same ease of use and transparency.

Not sure, depending on my availability I will resurrect the `ecto-rethinkdb` which was created by a friend of mine.

I'm sorry if I have brought unnecessary discussion to this project, I wanted was to hear from yours.

For me this issue can even be closed after that conversation.

**Comment by joshua1** [comment]
@hamiltop The LINQ like query for one would be a nice to have with rethinkdb

**Comment by hamiltop** [comment]
I'm not convinced it adds much other than "This is the flavor I prefer". RethinkDB does not have a query language. It is a binary protocol with a rich library built on top of it.

The main argument I see is being able to drop rethinkDB into Ecto as a DB replacement without changing your models.

As it stands now, I'm not giving this much priority. I am, however, committed to keeping this around as a possibility (and avoiding design decisions that would make this more difficult).

**Comment by joshua1** [comment]
It's better that way.being able to drop rethink db into Ecto would be
really great to have as a Ecto brings a lot of ease to Phoenix app
development

**Comment by jeregrine** [comment]
@joshua1 phoenix and ecto are actually seperate projects, to use ecto in your phoenix you need a secondary lib https://github.com/phoenixframework/phoenix_ecto 

To use rethinkdb-elixir + phoenix you just could. Nothing in phoenix depends on ecto. If you want the form generators from phoenix_ecto you'd just need to reproduce this file https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/html.ex

**Comment by hamiltop** [comment]
I'd also point out that a huge difference between rethinkdb and SQL is the
thevyeacy dependence on lambdas in the query language. Adding a translation
layer between Ecto's syntax and rethinkDB is likely going to either be very
quirky or somewhat crippled.

I'm more than willing to support someone else try building a rethinkdb_ecto
lib, I'm just not planning on doing it myself.

**Comment by hamiltop** [comment]
I'm going to close this. I think a better starting point for this discussion is in https://github.com/hamiltop/rethinkdb-elixir/issues/45 .  TLDR; The notion of models is interesting and I think a lot of boilerplate can be taken care of through a Model macro (either from Ecto or a standalone one in this library). I want to incrementally explore that rather than jump to a big conclusion that everything must be exactly like Ecto.
