### ISSUE TITLE
Allow keywords as query opts

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/rethinkdb-elixir#66]
Mentioned in https://github.com/hamiltop/rethinkdb-elixir/issues/65

Implementation is in branch `keywords_as_opts`

The current implementation in master detects opts using `is_map(opts)`. In the branch we do `is_map(opts) or is_list(opts)`. This can get screwy when there is an optional last argument in the query that accepts a list. Most if not all of these cases don't accept opts so we should be alright, but I want someone to verify that we aren't breaking things.

If anyone wants to help, then I'd recommend going through https://rethinkdb.com/api/ruby/ one section at a time and verifying that all functions in that section behave properly.

Note: We deviate from the Ruby api in cases where varargs are required (as they are not supported in Elixir). In those cases we accept a single list of args.

See also http://hexdocs.pm/rethinkdb/0.1.1/ for the elixir functions implemented.

**Comment by hamiltop** [comment]
I'm verifying the Math and Logic section

**Comment by hamiltop** [comment]
Math and Logic looks good.

**Comment by almightycouch** [comment]
Following functions have been tested successfully (all functions taking optional `opts` arg):
* `RethinkDB.Query.table_create()`
* `RethinkDB.Query.index_create()` (_without nested fields_)
* `RethinkDB.Query.index_rename()`
* `RethinkDB.Query.insert()`
* `RethinkDB.Query.update()`
* `RethinkDB.Query.replace()`
* `RethinkDB.Query.delete()`
* `RethinkDB.Query.table()`
* `RethinkDB.Query.get_all()`
* `RethinkDB.Query.between()`
* `RethinkDB.Query.filter()`
* `RethinkDB.Query.eq_join()`
* `RethinkDB.Query.slice()`
* `RethinkDB.Query.min()`
* `RethinkDB.Query.max()`
* `RethinkDB.Query.distinct()`
* `RethinkDB.Query.iso8601()`
* `RethinkDB.Query.during()`

I found following inconsistencies with the [Ruby API](https://rethinkdb.com/api/ruby/):
* `RethinkDB.Connection.run()` does not allow options.
* `RethinkDB.Query.changes()` does not allow options.
* `RethinkDB.Query.get_all()` should accept single key for the first arg (`1` instead of `[1]`).
* `RethinkDB.Query.order_by()` does not allow options (`index: desc("date")`).
* `RethinkDB.Query.slice()` second arg (`end_index`) should be optional.
* `RethinkDB.Query.group()` does not allow options.
* `RethinkDB.Query.http()` does not allow options as `Keyword` list (works with `Map`).


I did not try any of the geospacial commands: `circle`, `distance`, `get_intersecting`, `get_nearest`.

**Comment by hamiltop** [comment]
Awesome! I'll take a look at the inconsistencies.
