### ISSUE TITLE
Add helpful errors for when a user doesn't follow default connection naming conventions

### ISSUE THREAD

**Issue by ryanswapp** [hamiltop/rethinkdb-elixir#76]
Per our conversation [here](http://ryanswapp.com/2015/11/28/getting-started-with-rethinkdb-and-phoenix-framework/#disqus_thread), it would be nice to have helpful errors to notify a user when they aren't following the default connection naming conventions.

**Comment by hamiltop** [comment]
Is this an Error or a warning situation? As it currently stands, the only value in calling `use` is to take advantage of the naming, so it should probably be an error. I have some ideas in the future for providing other options when calling `use`, but we can soften it to a warning then if it makes sense.

FYI, https://github.com/hamiltop/rethinkdb-elixir/blob/master/lib/rethinkdb/connection.ex#L49 is the code that `use RethinkDB.Connection` adds. Basically what you did by hand, except it uses `__MODULE__` as the process name everywhere. I like your example because it is "magic free". Can you add a link to your blog in the Wiki here?

**Comment by hamiltop** [comment]
```elixir
defmodule TestConnection do
  use RethinkDB.Connection
end

TestConnection.start_link(name: :test)
** (ArgumentError) Process name :test conflicts with implicit name TestConnection
    iex:2: TestConnection.start_link/1
```

@ryanswapp Would that error have been descriptive enough?

**Comment by ryanswapp** [comment]
I agree that if the only reason to use ```use RethinkDB.Connection``` is to get the naming conventions then an error should be thrown if the naming conventions are broken. 

Hmm... In looking at the proposed error message I'm wondering if I would have known what it meant prior to you explaining the purpose of ```use RethinkDB.Connection```. Would it bad to make the error a little more descriptive? Perhaps something like "Process name :test conflicts with implicit name TestConnection. Default connections implicitly name the database connection process after the module where use RethinkDB.Connection is declared." The sentence I added is a little rough around the edges but I just wanted to offer an example of what I think might better help a newcomer to understand what they are doing wrong. Thoughts?

Just added a link to my tutorial in the wiki.

**Comment by hamiltop** [comment]
Going with:

```
TestConnection.start_link(name: :test)
** (ArgumentError) Process name :test conflicts with implicit name TestConnection provided by `use RethinkDB.Connection`
    lib/rethinkdb/connection.ex:56: TestConnection.start_link/1
```

**Comment by ryanswapp** [comment]
Nice. I think that should work. The "by 'use RethinkDB.Connection'" bit would have pointed me directly to the problem.

**Comment by hamiltop** [comment]
pushed, published to hex.pm (along with a few other tweaks from the past few weeks) as version 0.2.1, docs uploaded.

I added a section about the error at http://hexdocs.pm/rethinkdb/RethinkDB.Connection.html#__using__/1
