### ISSUE TITLE
Order by descending returns error "Third element in a Term is not optional arguments."

### ISSUE THREAD

**Issue by sikanhe** [hamiltop/rethinkdb-elixir#87]
To reproduce, simply adding this test under query_test.exs

    test "order by descending attr" do
      data = [%{rank: 1}, %{rank: 2}, %{rank: 3}]

      table(@table_name)
      |> insert(data)
      |> run

      %{data: result} = table(@table_name)
                    |> order_by(desc("rank"))
                    |> run

      assert result == Enum.reverse(data)
    end

**Comment by hamiltop** [comment]
This is a bit rough.

`order_by` can be called in the following ways:

`order_by(selection, key)`

`order_by(selection, %{index: key})`

`order_by(selection, desc(key))`

`order_by(selection, [key1, key2])`

The problem here is that `desc(key)` builds a `%RethinkDB.Q{}` struct. Structs are maps. So there isn't an easy way to differentiate between `%{index: key}` and `%RethinkDB.Q{}` at a high level.

Most of the query implementation is built on top of macros that are shared, so you just specify the arity and the macro creates the function for you.

I suspect you might find similar behavior if you passed a subquery that returns a key. You would see this also happening with `min` and `max`.

I have a fix though. I'm not thrilled with it, but will work.

Fix is in master, 5d0548b

**Comment by lelongking** [comment]
Hi hamiltop,
you help me, order_by can be called:

order_by(selection, [desc(key1), key2])
