### ISSUE TITLE
Support for Atom Keys

### ISSUE THREAD

**Issue by robconery** [hamiltop/rethinkdb-elixir#89]
Thanks for your work on this - been using it for an app I'm building and it's quite nice but I've run into a few snags. This first is rather simple but I thought I would ask: is there a reason you're going with Poison's default string keys?

I believe you can simply do an options here:
https://github.com/hamiltop/rethinkdb-elixir/blob/8e6821c3ea1794bd0d108f496bac7251883e47bd/lib/rethinkdb/response.ex#L44

By setting: 

```
decode!(json, keys: :atoms!)
```

I'm happy to PR this but I suppose it could be considered a breaking change? Or, possibly, maybe there could be a config option to opt into such as `atom_keys: true`?

**Comment by hamiltop** [comment]
I've been contemplating this. I've stuck to the safe side of things for now, but I've been trying to decide what the right behavior is when atoms that aren't already existing would be created. Here are the options I've come up with:

* Current behavior - only do string keys.
* Raise if non atom keys are encountered. - This would be pretty inconvenient if you had multiple DB consumers, since someone adding a key from a separate application would break your application.
* Ignore non atom keys - This seems like a bad idea, since read-modify-write cycles would truncate data.
* Try to convert to atom and if it fails leave the string key - This feels messy and not very explicit, but it's very safe.
* Provide a whitelist for atom keys - A bit more explicit, but leaves things still mixed.

There's always the possibility of supporting all of them. Also, if we leave string keys as the default then we sort of just assume people know what they are doing and bad consequences are their own fault.

I'm happy to add this functionality, just need some feedback from users to know which will be best (or perhaps least terrible).

**Comment by robconery** [comment]
I think that Poison will default to string keys always - sorry if I didn't make myself clear but I was only thinking about reads. You can decode and tell Poison to make the keys atoms. It's what I defaulted to with Moebius (the PG lib) because it's a bit more idiomatic (from what I've read) and it's a little easier to read with dot notation.

**Comment by hamiltop** [comment]
Yep, Poison defaults to string keys, but if you specify `:atoms!` it will raise if it encounters one that doesn't already exist. If you specify `:atoms` then you risk overloading the vm with atoms that aren't garbage collected.

A schema'd db can fairly easily provide a guarantee that any keys will already be existing atoms, but a schemaless db like RethinkDB has more exposure. That's my concern here. Regardless of what we decided to add, string keys will be the default.

**Comment by robconery** [comment]
I don't know if I follow - Poison is simply parsing the document for you - in what case would a key not exist? I can see an issue where two of the same key exists (with JSON) but with Rethink that's not allowed. 

I also don't follow the "overloading the vm" part.

**Comment by hamiltop** [comment]
Let's take a step outside of RethinkDB and talk about JSON decoding.

Assume you have an HTTP endpoint that is accepting JSON as data. Let's say you were to parse all incoming JSON into maps with atom keys. I, a malicious individual, could spam your endpoint with random JSON (`{"a": 1, "aa" : 1, "aaa" : 1, ... }`). You would parse each new key into an atom. Atoms, once created, are not garbage collected. I would eventually bring down your server by consuming all available memory (or the VM would just quit once it reached the hard limit for atom creation).

That's a real documented problem. That's why Poison has `keys: :atom!` and `keys: :atom`. With `keys: atom!`, it calls `String.to_existing_atom` which will raise an exception unless that atom already exists on the VM. Most of the time, that's fine, because you defined a Struct somewhere and that causes each of the atom keys to be defined already. The result is that there is no chance of a memory leak.

In a schema'd db, you have a finite set of keys available. Even if you were to encounter a key for the first time, it's unlikely to bite you too badly. With a schemaless db, we have no guarantees at the db level. You could explicitly whitelist all keys being written to or read from the database and it would solve the problem at the application level. However, that's not a guarantee _I_ can provide in the driver, so I err on the side of caution.

Does that clarify things?

**Comment by robconery** [comment]
I am not sure - I'm new to all this so forgive me if my thoughts are off...

> I would eventually bring down your server by consuming all available memory (or the VM would just quit once it reached the hard limit for atom creation

From what I understand, each process has its own heap, so garbage collection is fairly straightforward. It seems odd to me that Erlang could be brought down by an accumulation of stray atoms.

> it calls String.to_existing_atom which will raise an exception unless that atom already exists on the VM. Most of the time, that's fine, because you defined a Struct somewhere and that causes each of the atom keys to be defined already. The result is that there is no chance of a memory leak.

As I mention, I'm new to all of this. But I'm using `keys : atom!` with Moebius and the PostgreSQL JSONB stuff. I haven't run into these problems, and we don't use structs. In fact I bypass the encoder altogether and just push a string directly in - decoding on the way out because Poison is a bit difficult to deal with.

It would be interesting to hear @josevalim's thoughts here - he's helped me to no end with these things and this conversation is quite fascinating!

**Comment by hamiltop** [comment]
So... I dove into `moebius` and here's what's happening:

```
iex(6)> Moebius.DocumentQuery.db(:documents) |> Moebius.DocumentQuery.first
** (ArgumentError) argument error
              :erlang.binary_to_existing_atom("last_name", :utf8)
              lib/poison/parser.ex:97: Poison.Parser.object_name/2
              lib/poison/parser.ex:82: Poison.Parser.object_pairs/3
              lib/poison/parser.ex:78: Poison.Parser.object_pairs/3
              lib/poison/parser.ex:36: Poison.Parser.parse/2
              lib/poison/parser.ex:50: Poison.Parser.parse!/2
              lib/poison.ex:83: Poison.decode!/2
    (moebius) lib/moebius/document_query.ex:512: Moebius.DocumentQuery.handle_row/1
```

vs

```
iex(1)> Moebius.Query.db(:books) |> Moebius.Query.first
%{data: %{"author" => %{"first_name" => "Bob", "last_name" => "White"},
    "name" => "Book the First"}, id: 1}
```

Note: I had the same json in both json fields `{ "name": "Book the First", "author": { "first_name": "Bob", "last_name": "White" }`. For `DocumentQuery` you use poison with `:atoms!` and it throws the exception. For `Query` you are treating them as strings and all is good.

Here's an even more interesting case:

```
iex(2)> Moebius.DocumentQuery.db(:documents) |> Moebius.DocumentQuery.first
** (ArgumentError) argument error
              :erlang.binary_to_existing_atom("last_name", :utf8)
              lib/poison/parser.ex:97: Poison.Parser.object_name/2
              lib/poison/parser.ex:82: Poison.Parser.object_pairs/3
              lib/poison/parser.ex:78: Poison.Parser.object_pairs/3
              lib/poison/parser.ex:36: Poison.Parser.parse/2
              lib/poison/parser.ex:50: Poison.Parser.parse!/2
              lib/poison.ex:83: Poison.decode!/2
    (moebius) lib/moebius/document_query.ex:512: Moebius.DocumentQuery.handle_row/1
iex(2)> :author
:author
iex(3)> :first_name
:first_name
iex(4)> :last_name
:last_name
iex(5)> :name
:name
iex(6)> Moebius.DocumentQuery.db(:documents) |> Moebius.DocumentQuery.first
%{author: %{first_name: "Bob", last_name: "White"}, id: 1,
  name: "Book the First"}
```

You can see, that merely typing `:author` and hitting enter creates the atom and Poison can use it to decode the JSON.

As I said, this is very well established as a limitation. A similar limitation exists on pretty much every platform that utilizes atoms. Ruby has the same problem with symbols. They are global because they are inherently shared data. Atoms are used to translate string-ish keys to and from numerical values. Lookups from an atom key are much faster than from a string key in a map because the string does not need to be hashed. They have to be shared because the resolution of a particular atom must be consistent across the VM.

Hope that clarifies things a bit.

**Comment by josevalim** [comment]
> From what I understand, each process has its own heap, so garbage collection is fairly straightforward. It seems odd to me that Erlang could be brought down by an accumulation of stray atoms.

Not all data is stored in the process heap. Some of this data is shared and atoms is one of them. It makes complete sense when you understand the purpose of atoms: they are meant to be readable values that are extremely fast to compare. For example, we could return from `File.read` something like `{0, "contents"}` or `{1, "error"}` but that is not readable, so you introduce `:ok` and `:error` and try to make it as fast as comparing integers.

For it to be fast, you need to have a global table that translate the atom to an integer. It could have been per process but that would duplicate a good chunk of the table on every process and would make interprocess communication more expensive (because you know have to send the whole atom instead of the integer).

Atoms could be garbage collected but, if the integer they point to changes, it means you need to do multiple lookups which again, affects their performance characteristics.

**Comment by robconery** [comment]
Thanks for the explanations! Much appreciated :). And I just learned something crazy! @hamiltop I was wondering, as I read your post above, how in the world our tests were passing and it was simply because (as you say) we were inserting the data first using a keyword list - which created the atoms and there you are.

Fascinating discussion - I think I'm going to lob an issue right now for reverting to string keys with Moebius :). Makes perfect sense now - though I wish dot notation was available for them but... Oh well I can get over that.

Cheers gents!
